spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wds
    username: WDS
    password: '@WDS1024'
mybatis:
  configuration:
    map-underscore-to-camel-case: true #下划线命名与驼峰命名的自动转换

